### ISSUE TITLE
Action Fails

### ISSUE THREAD

**Issue by ebebbington** [bluwy/release-for-reddit-action#5]
![image](https://user-images.githubusercontent.com/47337480/98445829-b339c380-2111-11eb-94e0-1080f7eddc08.png)

When running:
```yml
name: master
on: release

jobs:
  socials:
    runs-on: ubuntu-latest
    steps:
      - uses: bluwy/release-for-reddit-action@v1
        with:
          username: ${{ secrets.REDDIT_USERNAME }}
          password: ${{ secrets.REDDIT_PASSWORD }}
          app-id: ${{ secrets.REDDIT_APP_ID }}
          app-secret: ${{ secrets.REDDIT_APP_SECRET }}
          subreddit: Deno
          comment: "test"
          url: ${{ github.event.release.html_url }}
```
